### PR TITLE
Check interpolated stop times

### LINKED ISSUE #892: Validateur GTFS trop exigeant
Message de Zenbus qui visiblement respecte les normes GTFS mais se fait refuser par notre validateur

---

Bonjour,

Nous avons remarqué que l'erreur de type échec irrécupérable "error while reading stop_times.txt: CSV deserialize error: {...}: cannot parse integer from empty string " apparaît suite à l'absence d'un horaire sur un trip. C'est à dire si dans le fichier GTFS stop_times.txt, les champs arrival_time et/ou departure_time ne sont pas renseignés.
Selon les spécifications du GTFS, ces champs sont facultatifs. Ils sont obligatoires uniquement pour les terminus départs et arrivés :
image-zb1

Nous avons des réseaux pour lesquels seuls les arrêts majeurs ont un horaire théorique. Dans le cas de Moselle et Madon cela concernait un trip présent dans un calendrier ancien qui n'était plus en cours de validation. Nous avons effectivement modifier la modélisation de Moselle et Madon, GPSO et Saintes (visible demain) pour que l'erreur n'apparaisse plus pour le moment. Nous n'avons pas fait de modification sur Rosny sous bois. En ce qui concerne Auch nous sommes dans le cas où ce sont des arrêts intermédiaires qui ne sont pas renseignés :

image-zb2

Pouvez-vous modifier la validation des GTFS pour prendre en compte le côté facultatif de ces champs ?

### PR DESCRIPTION
**Pull request by antoine-de**
Add a rule to check that neither the first nor the last stoptime of a
trip have an undefined departure/arrival.

Also upgrade gtfs-structures to be able to handle the undefined
departure/arrival :wink:

depends on https://github.com/rust-transit/gtfs-structure/pull/45 (so I need to update the Cargo.toml after the merge)

closes https://github.com/etalab/transport-site/issues/892

### CODE REVIEW

File: src/validators/mod.rs [hunk 1]
```diff
@@ -92,16 +94,7 @@ pub fn validate_and_metadata(rgtfs: gtfs_structures::RawGtfs, max_issues: usize)
...
-        log::info!("Starting download of {}", input);
-        let result = gtfs_structures::RawGtfs::from_url(input);
-        log::info!("Download done of {}", input);
-        result
-    } else if input.to_lowercase().ends_with(".zip") {
-        gtfs_structures::RawGtfs::from_zip(input)
-    } else {
-        gtfs_structures::RawGtfs::new(input)
-    };
+    let raw_gtfs = gtfs_structures::RawGtfs::new(input);
```
Comment (Tristramg) [inline src/validators/mod.rs:97]: yeah ;)

**Review by Tristramg — APPROVED** [review]
